site_name: Twitter Frontline
pages:
  - Main: index.md
  - Installation: install.md
  - Windows:
    - retweet.exe: retweet.md
    - twitterhelpbot.exe: twitterhelpbot.md
    - tweetall.exe: tweetall.md
  - Raspberry Pi: pi.md
#  - Python 進階: python.md
theme: readthedocs
