site_name: Twitter Frontline
nav:
  - Home: index.md
  - Installation: install.md
  - config.ini: config.md
  - Windows:
    - retweet.exe: retweet.md
    - twitterhelpbot.exe: twitterhelpbot.md
    - tweetall.exe: tweetall.md
  - Raspberry Pi: pi.md
#  - Python 進階: python.md
theme: readthedocs
