site_name: Twitter 戰線
pages:
  - 主頁: index.md
  - 安裝: install.md
  - Windows:
    - retweet.exe: retweet.md
    - twitterhelpbot.exe: twitterhelpbot.md
    - tweetall.exe: tweetall.md
  - Raspberry Pi: pi.md
#  - Python 進階: python.md
theme: readthedocs
